package com.hireconnect.notification.entity;

public enum NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_STATUS_CHANGED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_CONFIRMED,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_CANCELLED,
    JOB_APPLICATION_DEADLINE,
    NEW_JOB_POSTED,
    PROFILE_VIEWED,
    MESSAGE_RECEIVED,
    SYSTEM_ANNOUNCEMENT,
    PAYMENT_SUCCESS,
    SUBSCRIPTION_RENEWAL,
    SECURITY_ALERT,
    USER_REGISTERED,
    PASSWORD_RESET
}
